/**
 * Supabase Database Types
 * This file will be auto-generated by Supabase CLI in production
 * For now, we define a basic structure
 */

import { Location, User, SavedLocation } from './database';

export type Database = {
  public: {
    Tables: {
      users: {
        Row: User;
        Insert: Omit<User, 'id' | 'created_at'>;
        Update: Partial<Omit<User, 'id' | 'created_at'>>;
      };
      locations: {
        Row: Location;
        Insert: Omit<Location, 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Omit<Location, 'id' | 'created_at' | 'updated_at'>>;
      };
      saved_locations: {
        Row: SavedLocation;
        Insert: Omit<SavedLocation, 'id' | 'saved_at'>;
        Update: Partial<Omit<SavedLocation, 'id' | 'saved_at'>>;
      };
    };
  };
};
